apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reqspace-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: reqspace-route
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: reqspace.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reqspace-web
            port:
              number: 80
