apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reqspace-web-ingress
spec:
  rules:
  - host: reqspace.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reqspace-web
            port:
              number: 80
